<a href="https://colab.research.google.com/github/nag-r/colab-notebooks/blob/main/Assignment_3_MSBA_May2021_Nag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Assignment 3: Data Structures, Loops, Functions

#### (10 pts) A. Nested Data Structures and Lists

The students received their grades for a midterm exam. The results came as a dictionary, and the grades are in the form of lists. The list contains the score each student received, for each question in the midterm. Unfortunately, the professor was very absent minded and he forgot to sum up the points to compute the overall grade for each student.

* (1pts) How many students are in the data set?
* (1pts) How many questions were in the midterm?
* (4pts) Write code to compute the overall grade of each student. Add the overall grade in a new dictionary called `midterm_grades`, with the students as keys, and the overall grades as (integer) values.
* (1pts) Extract the values from the `midterm_grades` and create a list of the overall grades for the midterm.
* (3pts) Compute the maximum, minimum, average, and median grade among the overall student grades.

In [ ]:
grades = {
    "studentA" : [5, 2, 3, 1, 2, 4, 5, 5, 1, 1],
    "studentB" : [1, 2, 5, 5, 2, 0, 1, 5, 5, 2],
    "studentC" : [2, 5, 5, 5, 5, 0, 1, 3, 1, 0],
    "studentD" : [0, 1, 0, 5, 2, 5, 1, 3, 3, 5],
    "studentE" : [5, 4, 5, 5, 1, 5, 1, 4, 4, 5],
    "studentF" : [2, 2, 1, 1, 1, 3, 1, 3, 0, 1],
    "studentG" : [5, 5, 5, 5, 5, 4, 3, 5, 3, 1],
}

# number of students
numberofstudents = len(grades.keys())
print(numberofstudents)

# number of questions
numberofquestions = len(grades["studentA"])
print(numberofquestions)

# overall grades

gradestudentA = sum (grades['studentA'])
gradestudentB = sum (grades['studentB'])
gradestudentC = sum (grades['studentC'])
gradestudentD = sum (grades['studentD'])
gradestudentE = sum (grades['studentE'])
gradestudentF = sum (grades['studentF'])
gradestudentG = sum (grades['studentG'])

midterm_grades = {
    "studentA" : gradestudentA,
    "studentB" : gradestudentB,
    "studentC" : gradestudentC,
    "studentD" : gradestudentD,
    "studentE" : gradestudentE,
    "studentF" : gradestudentF,
    "studentG" : gradestudentG,
}

print(midterm_grades.values())

from statistics import mean, median
print("The maximum midterm grade is: ",max(midterm_grades.values()))
print("The minimum midterm grade is: ",min(midterm_grades.values()))
print("The average midterm grade is: ",round(mean(midterm_grades.values()),2))
print("The median midterm grade is: ",median(midterm_grades.values()))

7
10
dict_values([29, 28, 27, 25, 39, 15, 41])
The maximum midterm grade is:  41
The minimum midterm grade is:  15
The average midterm grade is:  29.14
The median midterm grade is:  28

#### (10 pts) B. Restaurant Meal Price 

* Part 1. (1pts) Write code that computes the total price of the meal in a restaurant. You know that:
    * The price of the food is $15.
    * The NY State Tax rate is 8.875%.
    * The tipping percentage is 18% of the the overall cost of the meal (including tax).
    * Use Python variables to perform the computation.

* Part 2. (2 pts) Write a function that computes the total price of the meal in a restaurant. The function takes as input the food price, the sales tax rate, and the tip percentage. The tip is computed on the overall cost of the meal (including tax).

* Part 3. (3 pts) Write a for loop that computes the total price of a meal, for different tipping rates, starting from 15% and ending at 25% (both inclusive) at 1% increments. Use the function from Part 2 as part of the loop.

* Part 4. (4 pts) Below you will find a dictionary with the tax rates for different states, expressed in percentiles. Iterate through all states and print the value of a meal, where the pre-tax food price is $20; show the prices for tip percentages of 15%, 20%, and 25%.

In [ ]:
tax = {
    "Alabama": 13.50, 
    "Alaska": 7,
    "Arizona": 10.73,
    "Arkansas": 11.63,
    "California": 10,
    "Colorado": 10,
    "Connecticut": 6.35,
    "Delaware": 0,
    "District of Columbia": 5.75,
    "Florida": 7.50,
    "Georgia": 8,
    "Hawaii": 4.50,
    "Idaho": 8.50,
    "Illinois": 9.75,
    "Indiana": 7,
    "Iowa": 7,
    "Kansas": 9.65,
    "Kentucky": 6,
    "Louisiana": 11,
    "Maine": 5.50,
    "Maryland": 6,
    "Massachusetts": 6.25,
    "Michigan": 6,
    "Minnesota": 7.88,
    "Mississippi": 7.25,
    "Missouri": 9.35,
    "Montana": 0,
    "Nebraska": 7.50,
    "Nevada": 8.10,
    "New Hampshire": 0,
    "New Jersey": 7,
    "New Mexico": 8.69,
    "New York": 8.88,
    "North Carolina": 7.50,
    "North Dakota": 8,
    "Ohio": 8,
    "Oklahoma": 11,
    "Oregon": 0,
    "Pennsylvania": 8,
    "Rhode Island": 7,
    "South Carolina": 9,
    "South Dakota": 6,
    "Tennessee": 9.75,
    "Texas": 8.25,
    "Utah": 8.35,
    "Vermont": 7,
    "Virginia": 6,
    "Washington": 9.60,
    "West Virginia": 7,
    "Wisconsin": 5.60,
    "Wyoming": 6,
}

# price of the meal in NY
foodpriceNY = 15
statetaxNY = tax["New York"]
tiprate = 0.18
totalmealpriceNY = (foodpriceNY + statetaxNY) + ((foodpriceNY + statetaxNY)*tiprate)
print('The total meal price in NY is: $',round(totalmealpriceNY,2))

# function for calculating price of the meal
def totalmealprice(foodprice,statetax,tippct):
  result = (foodprice + (statetax/100)) + ((foodprice + (statetax/100))*tippct/100)
  return result

# for loop to iterate from 15% to 25% inclusive with 1% increment. for this illustration we will consider food price is $10 and statetax is 1%
for tippct in range(15,26,1):
  print('The total meal price for $10 food and $1 tax rate is: $',round(totalmealprice(10,1,tippct),2))

# total meal price for all states
pretaxmealprice = 20
states = tax.keys()

for state in states:
  for tippct in range(15,30,5):
    print('The total meal price in ',state,'for a tip percentage of ',tippct,'% is: $',round(totalmealprice(pretaxmealprice,tax[state],tippct),2))

#### (5 pts) C. Search within a file 

The `curl` command below will download the file `restaurant-names.txt` from Github. 

For this assignment, your task is to read the file `restaurant-names.txt` (after downloading it) and answer the following questions:
* How many restaurants appear in the dataset?
* Print the restaurants that contain the word GREEK in their name.
* How many restaurants contain the word PIZZA in their name?

In [ ]:
!curl https://raw.githubusercontent.com/ipeirotis/introduction-to-python/master/data/restaurant-names.txt -o restaurant-names.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  364k  100  364k    0     0  1710k      0 --:--:-- --:--:-- --:--:-- 1710k

In [ ]:
import pandas as pd
# import the file 
rest_name = "https://raw.githubusercontent.com/ipeirotis/introduction-to-python/master/data/restaurant-names.txt"

rest_name_df = pd.read_table(rest_name,names=['Restaurent Name'])
print('Total number of restaurents :',rest_name_df.count())

# print the restaurent that contains the word GREEK in their name
greekname = rest_name_df[rest_name_df['Restaurent Name'].str.contains('GREEK')]
print('Total number of restaurents that has the word GREEK in it: ',greekname.count())
print(greekname)

# number of restaurents that contain word PIZZA
pizzanameoccurrence = rest_name_df['Restaurent Name'].str.contains('PIZZA')
print('Total number of restaurents that has the word PIZZA in it: ',pizzanameoccurrence.sum())

Total number of restaurents : Restaurent Name    20443
dtype: int64
Total number of restaurents that has the word GREEK in it:  Restaurent Name    23
dtype: int64
                              Restaurent Name
942                        ANTHI'S GREEK FOOD
1284                     AVLEE  GREEK KITCHEN
1285                      AVLEE GREEK KITCHEN
1286             AVLI THE LITTLE GREEK TAVERN
6186                      ETHOS GREEK CUISINE
7589                            GREEK EXPRESS
7590                     GREEK FAMILY KITCHEN
7591                      GREEK GARDENS GRILL
7592                              GREEK GRILL
7593                            GREEK ISLANDS
7680                          GRK FRESH GREEK
7750                         GYRO GREEK STYLE
11755      MEDITERRANEAN GRILL GREEK TARVERNA
13599                   OKEANOS GREEK SEAFOOD
13704                   OPA! GREEK RESTAURANT
15102                    RAFINA GREEK CUISINE
16729                         SOMETHING GREEK
17515              SYMPOSIUM GREEK RESTAURANT
18294                               THE GREEK
18295                        THE GREEK CORNER
18296  THE GREEK KITCHEN  CLINTON BAKERY CAFE
19642             VILLAGE TAVERNA GREEK GRILL
20386          ZENON TAVERNA GREEK RESTAURANT
Total number of restaurents that has the word PIZZA in it:  963

#### (5pts) D. Function that returns a dictionary 

Write a function that has a parameter that is the height of someone in centimeters. You need to convert it into feet and inches. (Each foot is 30.48 cm. Each inch is 2.54cm.). The function should return the height in feet and inches. The result should be a dictionary with two keys, `feet` and `inches`, and the values for both keys should be integers.

In [ ]:
def heightconverter(heightincm):
    inches = 0.3937 * heightincm
    feet = 0.0328 * heightincm
    height = {}
    height['feet'] = round(feet,2)
    height['inches'] = round(inches,2)
    return height

# test
print(heightconverter(150))

{'feet': 4.92, 'inches': 59.05}

(20 pts) E. Data Processing and Transformation

**Part 1** (6 points): `states` is a multiline string variable that contains three pieces of information about the 50 US states: the state abbreviation, full state name, and the state's capital city name. A dash (`-`) separates the abbreviation, state name, and capital. 

* Create a new variable, `states_list`. The `states_list` should be a list with 50 3-element lists. Each of the 3-element lists should contain, in this order, the state abbreviation, the state name, and the state capital. 

* Create a new variable, `states_dict` by analyzing the `states_list` from above. The `states_dict` should be a dictionary with 50 keys; the key for each entry should be the abbreviation for the state. The value for each key should be a 2-element dictionary, with two keys `state_name` and `state_capital`.

In [ ]:
states ="""AL-Alabama-Montgomery
AK-Alaska-Juneau
AZ-Arizona-Phoenix
AR-Arkansas-Little Rock
CA-California-Sacramento
CO-Colorado-Denver
CT-Connecticut-Hartford
DE-Delaware-Dover
FL-Florida-Tallahassee
GA-Georgia-Atlanta
HI-Hawaii-Honolulu
ID-Idaho-Boise
IL-Illinois-Springfield
IN-Indiana-Indianapolis
IA-Iowa-Des Moines
KS-Kansas-Topeka
KY-Kentucky-Frankfort
LA-Louisiana-Baton Rouge
ME-Maine-Augusta
MD-Maryland-Annapolis
MA-Massachusetts-Boston
MI-Michigan-Lansing
MN-Minnesota-St. Paul
MS-Mississippi-Jackson
MO-Missouri-Jefferson City
MT-Montana-Helena
NE-Nebraska-Lincoln
NV-Nevada-Carson City
NH-New Hampshire-Concord
NJ-New Jersey-Trenton
NM-New Mexico-Santa Fe
NY-New York-Albany
NC-North Carolina-Raleigh
ND-North Dakota-Bismarck
OH-Ohio-Columbus
OK-Oklahoma-Oklahoma City
OR-Oregon-Salem
PA-Pennsylvania-Harrisburg
RI-Rhode Island-Providence
SC-South Carolina-Columbia
SD-South Dakota-Pierre
TN-Tennessee-Nashville
TX-Texas-Austin
UT-Utah-Salt Lake City
VT-Vermont-Montpelier
VA-Virginia-Richmond
WA-Washington-Olympia
WV-West Virginia-Charleston
WI-Wisconsin-Madison
WY-Wyoming-Cheyenne"""

# create a list
stateslist = states.split('\n')
print(stateslist)
# create an empty list
states_list = []
for i in stateslist:
    states_list.append(i.split('-'))
print(states_list)

# create a dictionary of state list
states_dict = {}
for state in states_list:
    states_dict[state[0]] = [state[1], state[2]]

print(states_dict)

['AL-Alabama-Montgomery', 'AK-Alaska-Juneau', 'AZ-Arizona-Phoenix', 'AR-Arkansas-Little Rock', 'CA-California-Sacramento', 'CO-Colorado-Denver', 'CT-Connecticut-Hartford', 'DE-Delaware-Dover', 'FL-Florida-Tallahassee', 'GA-Georgia-Atlanta', 'HI-Hawaii-Honolulu', 'ID-Idaho-Boise', 'IL-Illinois-Springfield', 'IN-Indiana-Indianapolis', 'IA-Iowa-Des Moines', 'KS-Kansas-Topeka', 'KY-Kentucky-Frankfort', 'LA-Louisiana-Baton Rouge', 'ME-Maine-Augusta', 'MD-Maryland-Annapolis', 'MA-Massachusetts-Boston', 'MI-Michigan-Lansing', 'MN-Minnesota-St. Paul', 'MS-Mississippi-Jackson', 'MO-Missouri-Jefferson City', 'MT-Montana-Helena', 'NE-Nebraska-Lincoln', 'NV-Nevada-Carson City', 'NH-New Hampshire-Concord', 'NJ-New Jersey-Trenton', 'NM-New Mexico-Santa Fe', 'NY-New York-Albany', 'NC-North Carolina-Raleigh', 'ND-North Dakota-Bismarck', 'OH-Ohio-Columbus', 'OK-Oklahoma-Oklahoma City', 'OR-Oregon-Salem', 'PA-Pennsylvania-Harrisburg', 'RI-Rhode Island-Providence', 'SC-South Carolina-Columbia', 'SD-South Dakota-Pierre', 'TN-Tennessee-Nashville', 'TX-Texas-Austin', 'UT-Utah-Salt Lake City', 'VT-Vermont-Montpelier', 'VA-Virginia-Richmond', 'WA-Washington-Olympia', 'WV-West Virginia-Charleston', 'WI-Wisconsin-Madison', 'WY-Wyoming-Cheyenne']
[['AL', 'Alabama', 'Montgomery'], ['AK', 'Alaska', 'Juneau'], ['AZ', 'Arizona', 'Phoenix'], ['AR', 'Arkansas', 'Little Rock'], ['CA', 'California', 'Sacramento'], ['CO', 'Colorado', 'Denver'], ['CT', 'Connecticut', 'Hartford'], ['DE', 'Delaware', 'Dover'], ['FL', 'Florida', 'Tallahassee'], ['GA', 'Georgia', 'Atlanta'], ['HI', 'Hawaii', 'Honolulu'], ['ID', 'Idaho', 'Boise'], ['IL', 'Illinois', 'Springfield'], ['IN', 'Indiana', 'Indianapolis'], ['IA', 'Iowa', 'Des Moines'], ['KS', 'Kansas', 'Topeka'], ['KY', 'Kentucky', 'Frankfort'], ['LA', 'Louisiana', 'Baton Rouge'], ['ME', 'Maine', 'Augusta'], ['MD', 'Maryland', 'Annapolis'], ['MA', 'Massachusetts', 'Boston'], ['MI', 'Michigan', 'Lansing'], ['MN', 'Minnesota', 'St. Paul'], ['MS', 'Mississippi', 'Jackson'], ['MO', 'Missouri', 'Jefferson City'], ['MT', 'Montana', 'Helena'], ['NE', 'Nebraska', 'Lincoln'], ['NV', 'Nevada', 'Carson City'], ['NH', 'New Hampshire', 'Concord'], ['NJ', 'New Jersey', 'Trenton'], ['NM', 'New Mexico', 'Santa Fe'], ['NY', 'New York', 'Albany'], ['NC', 'North Carolina', 'Raleigh'], ['ND', 'North Dakota', 'Bismarck'], ['OH', 'Ohio', 'Columbus'], ['OK', 'Oklahoma', 'Oklahoma City'], ['OR', 'Oregon', 'Salem'], ['PA', 'Pennsylvania', 'Harrisburg'], ['RI', 'Rhode Island', 'Providence'], ['SC', 'South Carolina', 'Columbia'], ['SD', 'South Dakota', 'Pierre'], ['TN', 'Tennessee', 'Nashville'], ['TX', 'Texas', 'Austin'], ['UT', 'Utah', 'Salt Lake City'], ['VT', 'Vermont', 'Montpelier'], ['VA', 'Virginia', 'Richmond'], ['WA', 'Washington', 'Olympia'], ['WV', 'West Virginia', 'Charleston'], ['WI', 'Wisconsin', 'Madison'], ['WY', 'Wyoming', 'Cheyenne']]
{'AL': ['Alabama', 'Montgomery'], 'AK': ['Alaska', 'Juneau'], 'AZ': ['Arizona', 'Phoenix'], 'AR': ['Arkansas', 'Little Rock'], 'CA': ['California', 'Sacramento'], 'CO': ['Colorado', 'Denver'], 'CT': ['Connecticut', 'Hartford'], 'DE': ['Delaware', 'Dover'], 'FL': ['Florida', 'Tallahassee'], 'GA': ['Georgia', 'Atlanta'], 'HI': ['Hawaii', 'Honolulu'], 'ID': ['Idaho', 'Boise'], 'IL': ['Illinois', 'Springfield'], 'IN': ['Indiana', 'Indianapolis'], 'IA': ['Iowa', 'Des Moines'], 'KS': ['Kansas', 'Topeka'], 'KY': ['Kentucky', 'Frankfort'], 'LA': ['Louisiana', 'Baton Rouge'], 'ME': ['Maine', 'Augusta'], 'MD': ['Maryland', 'Annapolis'], 'MA': ['Massachusetts', 'Boston'], 'MI': ['Michigan', 'Lansing'], 'MN': ['Minnesota', 'St. Paul'], 'MS': ['Mississippi', 'Jackson'], 'MO': ['Missouri', 'Jefferson City'], 'MT': ['Montana', 'Helena'], 'NE': ['Nebraska', 'Lincoln'], 'NV': ['Nevada', 'Carson City'], 'NH': ['New Hampshire', 'Concord'], 'NJ': ['New Jersey', 'Trenton'], 'NM': ['New Mexico', 'Santa Fe'], 'NY': ['New York', 'Albany'], 'NC': ['North Carolina', 'Raleigh'], 'ND': ['North Dakota', 'Bismarck'], 'OH': ['Ohio', 'Columbus'], 'OK': ['Oklahoma', 'Oklahoma City'], 'OR': ['Oregon', 'Salem'], 'PA': ['Pennsylvania', 'Harrisburg'], 'RI': ['Rhode Island', 'Providence'], 'SC': ['South Carolina', 'Columbia'], 'SD': ['South Dakota', 'Pierre'], 'TN': ['Tennessee', 'Nashville'], 'TX': ['Texas', 'Austin'], 'UT': ['Utah', 'Salt Lake City'], 'VT': ['Vermont', 'Montpelier'], 'VA': ['Virginia', 'Richmond'], 'WA': ['Washington', 'Olympia'], 'WV': ['West Virginia', 'Charleston'], 'WI': ['Wisconsin', 'Madison'], 'WY': ['Wyoming', 'Cheyenne']}

**Part 2** (8 points) We provide additional information about the US states in the `states_info` dictionary variable. 

The keys for this dictionary are the states' abbreviations (like in the `states_dict` dictionary). The values for this dictionary are dictionaries of two elements:
* `population` key with an integer value that corresponds to the state population ([source](https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population)), and 
* `threeLargestCities` key with a dictionary value, where the dictonary contains the information about the three largest cities in the corresponding state: the keys being the city names and the values being the corresponding city populations ([source](https://www.infoplease.com/us/states)). 

Update the `states_info` dictionary by adding for each of the states the  information from the `states_dict` variable that we listed above.

  * set up a loop to go over the `states_info` items;
  * on each iteration, use the `states_info` key to obtain the corresponding information from the `states_dict` dictionary (the keys in these two dictionaries are the same); 
  * at the end, the `states_info` dictionary should contain 50 key-value pairs, where the keys are the state abbreviations, and the values are 4-item dictionaries with the `capital`, `nameOfState`, `population`, `threeLargestCities`.

In [ ]:
states_info = {
    "AL": {
        "population": 4921532,
        "threeLargestCities": {
            "Birmingham": 212461,
            "Montgomery": 200602,
            "Mobile": 194288,
        },
    },
    "AK": {
        "population": 731158,
        "threeLargestCities": {
            "Anchorage": 291826,
            "Fairbanks": 31535,
            "Juneau": 31275,
        },
    },
    "AZ": {
        "population": 7421401,
        "threeLargestCities": {
            "Phoenix": 1513367, 
            "Tucson": 526116, 
            "Mesa": 457587},
    },
    "AR": {
        "population": 3030522,
        "threeLargestCities": {
            "Little Rock": 197357,
            "Fort Smith": 87650,
            "Fayetteville": 78960,
        },
    },
    "CA": {
        "population": 39368078,
        "threeLargestCities": {
            "Los Angeles": 3884307,
            "San Diego": 1335896,
            "San Jose": 998537,
        },
    },
    "CO": {
        "population": 5807719,
        "threeLargestCities": {
            "Denver": 634265,
            "Northeast Jefferson": 451811,
            "Colorado Springs": 431834,
        },
    },
    "CT": {
        "population": 3557006,
        "threeLargestCities": {
            "Bridgeport": 146425,
            "New Haven": 130741,
            "Stamford": 125109,
        },
    },
    "DE": {
        "population": 986809,
        "threeLargestCities": {
            "Brandywine": 82672,
            "Wilmington": 71292,
            "Pike Creek-Central Kirkwood": 44493,
        },
    },
    "FL": {
        "population": 21733312,
        "threeLargestCities": {
            "Jacksonville": 836507,
            "Miami": 399457,
            "Tampa": 347645,
        },
    },
    "GA": {
        "population": 10710017,
        "threeLargestCities": {
            "Atlanta": 443775,
            "Augusta-Richmond": 197872,
            "Columbus": 185888,
        },
    },
    "HI": {
        "population": 1407006,
        "threeLargestCities": {
            "Honolulu": 374701, 
            "Ewa": 279683, 
            "Koolaupoko": 121180},
    },
    "ID": {
        "population": 1826913,
        "threeLargestCities": {
            "Boise": 212303, 
            "Nampa": 83930, 
            "Meridian": 80386},
    },
    "IL": {
        "population": 12587530,
        "threeLargestCities": {
            "Chicago": 2714856,
            "Aurora": 199932,
            "Rockford": 150843,
        },
    },
    "IN": {
        "population": 6754953,
        "threeLargestCities": {
            "Indianapolis": 834852,
            "Fort Wayne": 254555,
            "Evansville": 120235,
        },
    },
    "IA": {
        "population": 3163561,
        "threeLargestCities": {
            "Des Moines": 206688,
            "Cedar Rapids": 128119,
            "Davenport": 101363,
        },
    },
    "KS": {
        "population": 2913805,
        "threeLargestCities": {
            "Wichita": 385577,
            "Overland Park": 178919,
            "Kansas City": 147268,
        },
    },
    "KY": {
        "population": 4477251,
        "threeLargestCities": {
            "Lexington-Fayette": 305489,
            "Fayette": 286518,
            "Louisville": 262764,
        },
    },
    "LA": {
        "population": 4645318,
        "threeLargestCities": {
            "New Orleans": 369250,
            "Baton Rouge": 230058,
            "Shreveport": 201867,
        },
    },
    "ME": {
        "population": 1350141,
        "threeLargestCities": {
            "Portland": 66214, 
            "Lewiston": 36460, 
            "Bangor": 32817},
    },
    "MD": {
        "population": 6055802,
        "threeLargestCities": {
            "Baltimore": 621342,
            "Columbia": 99615,
            "Germantown": 86395,
        },
    },
    "MA": {
        "population": 6893574,
        "threeLargestCities": {
            "Boston": 636479,
            "Worcester": 182669,
            "Springfield": 153552,
        },
    },
    "MI": {
        "population": 9966555,
        "threeLargestCities": {
            "Detroit": 701475,
            "Grand Rapids": 190411,
            "Warren": 134141,
        },
    },
    "MN": {
        "population": 5657342,
        "threeLargestCities": {
            "Minneapolis": 392880,
            "St. Paul": 290770,
            "Rochester": 108992,
        },
    },
    "MS": {
        "population": 2966786,
        "threeLargestCities": {
            "Jackson": 175437,
            "Gulfport": 70113,
            "Southhaven": 50374,
        },
    },
    "MO": {
        "population": 6151548,
        "threeLargestCities": {
            "Kansas City": 464310,
            "St. Louis": 318172,
            "Springfield": 162191,
        },
    },
    "MT": {
        "population": 1080577,
        "threeLargestCities": {
            "Billings": 106954,
            "Missoula": 68394,
            "Great Falls": 58893,
        },
    },
    "NE": {
        "population": 1937552,
        "threeLargestCities": {
            "Omaha": 446599, 
            "Lincoln": 272996, 
            "Bellevue": 53936},
    },
    "NV": {
        "population": 3138259,
        "threeLargestCities": {
            "Las Vegas": 596424,
            "Henderson": 265679,
            "Reno": 231027,
        },
    },
    "NH": {
        "population": 1366275,
        "threeLargestCities": {
            "Manchester": 110209, 
            "Nashua": 86933, 
            "Concord": 42630},
    },
    "NJ": {
        "population": 8882371,
        "threeLargestCities": {
            "Newark": 277727,
            "Jersey City": 254441,
            "Paterson": 145219,
        },
    },
    "NM": {
        "population": 2106319,
        "threeLargestCities": {
            "Albuquerque": 555417,
            "Las Cruces": 101047,
            "Rio Rancho": 90818,
        },
    },
    "NY": {
        "population": 19336776,
        "threeLargestCities": {
            "New York": 8336697,
            "Buffalo": 259384,
            "Rochester": 210532,
        },
    },
    "NC": {
        "population": 10600823,
        "threeLargestCities": {
            "Charlotte": 775202,
            "Raleigh": 423179,
            "Greensboro": 277080,
        },
    },
    "ND": {
        "population": 765309,
        "threeLargestCities": {
            "Fargo": 109779,
            "Bismarck": 64751,
            "Grand Forks": 53456,
        },
    },
    "OH": {
        "population": 11693217,
        "threeLargestCities": {
            "Columbus": 787033,
            "Cleveland": 3968158,
            "Cincinnati": 296943,
        },
    },
    "OK": {
        "population": 3980783,
        "threeLargestCities": {
            "Oklahoma City": 579999,
            "Tulsa": 391906,
            "Norman": 110925,
        },
    },
    "OR": {
        "population": 4241507,
        "threeLargestCities": {
            "Portland": 583776, 
            "Eugene": 156185, 
            "Salem": 154637},
    },
    "PA": {
        "population": 12783254,
        "threeLargestCities": {
            "Philadelphia": 1526006,
            "Pittsburgh": 305704,
            "Allentown": 118032,
        },
    },
    "RI": {
        "population": 1057125,
        "threeLargestCities": {
            "Providence": 178042,
            "Warwick": 82672,
            "Cranston": 80387,
        },
    },
    "SC": {
        "population": 5218040,
        "threeLargestCities": {
            "Columbia": 129272,
            "Charleston": 120083,
            "North Charleston": 97471,
        },
    },
    "SD": {
        "population": 892717,
        "threeLargestCities": {
            "Sioux Falls": 153888,
            "Rapid City": 67956,
            "Aberdeen": 26091,
        },
    },
    "TN": {
        "population": 6886834,
        "threeLargestCities": {
            "Memphis": 646889,
            "Nashville": 626681,
            "Knoxville": 178874,
        },
    },
    "TX": {
        "population": 29360759,
        "threeLargestCities": {
            "Houston": 2099451,
            "San Antonio": 1327407,
            "Dallas": 1197816,
        },
    },
    "UT": {
        "population": 3249879,
        "threeLargestCities": {
            "Salt Lake City": 186440,
            "West Valley City": 129480,
            "Provo": 112488,
        },
    },
    "VT": {
        "population": 623347,
        "threeLargestCities": {
            "Burlington": 42417,
            "Essex": 19587,
            "South Burlington": 17993,
        },
    },
    "VA": {
        "population": 8590563,
        "threeLargestCities": {
            "Virginia Beach": 437994,
            "Norfolk": 242803,
            "Chesapeake": 222209,
        },
    },
    "WA": {
        "population": 7693612,
        "threeLargestCities": {
            "Seattle": 608660, 
            "Spokane": 208916, 
            "Tacoma": 198397},
    },
    "WV": {
        "population": 1784787,
        "threeLargestCities": {
            "Charleston": 51400,
            "Huntington": 49138,
            "Parkersburg": 31492,
        },
    },
    "WI": {
        "population": 5832655,
        "threeLargestCities": {
            "Milwaukee": 594833,
            "Madison": 233209,
            "Green Bay": 104057,
        },
    },
    "WY": {
        "population": 582328,
        "threeLargestCities": {
            "Cheyenne": 59011, 
            "Casper": 55316, 
            "Laramie": 30816},
    },
}

#set up a loop to go over the states_info items;
for abbre in states_info:
    if abbre in states_dict:
        states_info[abbre]["nameofState"] = states_dict[abbre][0]
        states_info[abbre]["capital"] = states_dict[abbre][1]
print(states_info)

{'AL': {'population': 4921532, 'threeLargestCities': {'Birmingham': 212461, 'Montgomery': 200602, 'Mobile': 194288}, 'nameofState': 'Alabama', 'capital': 'Montgomery'}, 'AK': {'population': 731158, 'threeLargestCities': {'Anchorage': 291826, 'Fairbanks': 31535, 'Juneau': 31275}, 'nameofState': 'Alaska', 'capital': 'Juneau'}, 'AZ': {'population': 7421401, 'threeLargestCities': {'Phoenix': 1513367, 'Tucson': 526116, 'Mesa': 457587}, 'nameofState': 'Arizona', 'capital': 'Phoenix'}, 'AR': {'population': 3030522, 'threeLargestCities': {'Little Rock': 197357, 'Fort Smith': 87650, 'Fayetteville': 78960}, 'nameofState': 'Arkansas', 'capital': 'Little Rock'}, 'CA': {'population': 39368078, 'threeLargestCities': {'Los Angeles': 3884307, 'San Diego': 1335896, 'San Jose': 998537}, 'nameofState': 'California', 'capital': 'Sacramento'}, 'CO': {'population': 5807719, 'threeLargestCities': {'Denver': 634265, 'Northeast Jefferson': 451811, 'Colorado Springs': 431834}, 'nameofState': 'Colorado', 'capital': 'Denver'}, 'CT': {'population': 3557006, 'threeLargestCities': {'Bridgeport': 146425, 'New Haven': 130741, 'Stamford': 125109}, 'nameofState': 'Connecticut', 'capital': 'Hartford'}, 'DE': {'population': 986809, 'threeLargestCities': {'Brandywine': 82672, 'Wilmington': 71292, 'Pike Creek-Central Kirkwood': 44493}, 'nameofState': 'Delaware', 'capital': 'Dover'}, 'FL': {'population': 21733312, 'threeLargestCities': {'Jacksonville': 836507, 'Miami': 399457, 'Tampa': 347645}, 'nameofState': 'Florida', 'capital': 'Tallahassee'}, 'GA': {'population': 10710017, 'threeLargestCities': {'Atlanta': 443775, 'Augusta-Richmond': 197872, 'Columbus': 185888}, 'nameofState': 'Georgia', 'capital': 'Atlanta'}, 'HI': {'population': 1407006, 'threeLargestCities': {'Honolulu': 374701, 'Ewa': 279683, 'Koolaupoko': 121180}, 'nameofState': 'Hawaii', 'capital': 'Honolulu'}, 'ID': {'population': 1826913, 'threeLargestCities': {'Boise': 212303, 'Nampa': 83930, 'Meridian': 80386}, 'nameofState': 'Idaho', 'capital': 'Boise'}, 'IL': {'population': 12587530, 'threeLargestCities': {'Chicago': 2714856, 'Aurora': 199932, 'Rockford': 150843}, 'nameofState': 'Illinois', 'capital': 'Springfield'}, 'IN': {'population': 6754953, 'threeLargestCities': {'Indianapolis': 834852, 'Fort Wayne': 254555, 'Evansville': 120235}, 'nameofState': 'Indiana', 'capital': 'Indianapolis'}, 'IA': {'population': 3163561, 'threeLargestCities': {'Des Moines': 206688, 'Cedar Rapids': 128119, 'Davenport': 101363}, 'nameofState': 'Iowa', 'capital': 'Des Moines'}, 'KS': {'population': 2913805, 'threeLargestCities': {'Wichita': 385577, 'Overland Park': 178919, 'Kansas City': 147268}, 'nameofState': 'Kansas', 'capital': 'Topeka'}, 'KY': {'population': 4477251, 'threeLargestCities': {'Lexington-Fayette': 305489, 'Fayette': 286518, 'Louisville': 262764}, 'nameofState': 'Kentucky', 'capital': 'Frankfort'}, 'LA': {'population': 4645318, 'threeLargestCities': {'New Orleans': 369250, 'Baton Rouge': 230058, 'Shreveport': 201867}, 'nameofState': 'Louisiana', 'capital': 'Baton Rouge'}, 'ME': {'population': 1350141, 'threeLargestCities': {'Portland': 66214, 'Lewiston': 36460, 'Bangor': 32817}, 'nameofState': 'Maine', 'capital': 'Augusta'}, 'MD': {'population': 6055802, 'threeLargestCities': {'Baltimore': 621342, 'Columbia': 99615, 'Germantown': 86395}, 'nameofState': 'Maryland', 'capital': 'Annapolis'}, 'MA': {'population': 6893574, 'threeLargestCities': {'Boston': 636479, 'Worcester': 182669, 'Springfield': 153552}, 'nameofState': 'Massachusetts', 'capital': 'Boston'}, 'MI': {'population': 9966555, 'threeLargestCities': {'Detroit': 701475, 'Grand Rapids': 190411, 'Warren': 134141}, 'nameofState': 'Michigan', 'capital': 'Lansing'}, 'MN': {'population': 5657342, 'threeLargestCities': {'Minneapolis': 392880, 'St. Paul': 290770, 'Rochester': 108992}, 'nameofState': 'Minnesota', 'capital': 'St. Paul'}, 'MS': {'population': 2966786, 'threeLargestCities': {'Jackson': 175437, 'Gulfport': 70113, 'Southhaven': 50374}, 'nameofState': 'Mississippi', 'capital': 'Jackson'}, 'MO': {'population': 6151548, 'threeLargestCities': {'Kansas City': 464310, 'St. Louis': 318172, 'Springfield': 162191}, 'nameofState': 'Missouri', 'capital': 'Jefferson City'}, 'MT': {'population': 1080577, 'threeLargestCities': {'Billings': 106954, 'Missoula': 68394, 'Great Falls': 58893}, 'nameofState': 'Montana', 'capital': 'Helena'}, 'NE': {'population': 1937552, 'threeLargestCities': {'Omaha': 446599, 'Lincoln': 272996, 'Bellevue': 53936}, 'nameofState': 'Nebraska', 'capital': 'Lincoln'}, 'NV': {'population': 3138259, 'threeLargestCities': {'Las Vegas': 596424, 'Henderson': 265679, 'Reno': 231027}, 'nameofState': 'Nevada', 'capital': 'Carson City'}, 'NH': {'population': 1366275, 'threeLargestCities': {'Manchester': 110209, 'Nashua': 86933, 'Concord': 42630}, 'nameofState': 'New Hampshire', 'capital': 'Concord'}, 'NJ': {'population': 8882371, 'threeLargestCities': {'Newark': 277727, 'Jersey City': 254441, 'Paterson': 145219}, 'nameofState': 'New Jersey', 'capital': 'Trenton'}, 'NM': {'population': 2106319, 'threeLargestCities': {'Albuquerque': 555417, 'Las Cruces': 101047, 'Rio Rancho': 90818}, 'nameofState': 'New Mexico', 'capital': 'Santa Fe'}, 'NY': {'population': 19336776, 'threeLargestCities': {'New York': 8336697, 'Buffalo': 259384, 'Rochester': 210532}, 'nameofState': 'New York', 'capital': 'Albany'}, 'NC': {'population': 10600823, 'threeLargestCities': {'Charlotte': 775202, 'Raleigh': 423179, 'Greensboro': 277080}, 'nameofState': 'North Carolina', 'capital': 'Raleigh'}, 'ND': {'population': 765309, 'threeLargestCities': {'Fargo': 109779, 'Bismarck': 64751, 'Grand Forks': 53456}, 'nameofState': 'North Dakota', 'capital': 'Bismarck'}, 'OH': {'population': 11693217, 'threeLargestCities': {'Columbus': 787033, 'Cleveland': 3968158, 'Cincinnati': 296943}, 'nameofState': 'Ohio', 'capital': 'Columbus'}, 'OK': {'population': 3980783, 'threeLargestCities': {'Oklahoma City': 579999, 'Tulsa': 391906, 'Norman': 110925}, 'nameofState': 'Oklahoma', 'capital': 'Oklahoma City'}, 'OR': {'population': 4241507, 'threeLargestCities': {'Portland': 583776, 'Eugene': 156185, 'Salem': 154637}, 'nameofState': 'Oregon', 'capital': 'Salem'}, 'PA': {'population': 12783254, 'threeLargestCities': {'Philadelphia': 1526006, 'Pittsburgh': 305704, 'Allentown': 118032}, 'nameofState': 'Pennsylvania', 'capital': 'Harrisburg'}, 'RI': {'population': 1057125, 'threeLargestCities': {'Providence': 178042, 'Warwick': 82672, 'Cranston': 80387}, 'nameofState': 'Rhode Island', 'capital': 'Providence'}, 'SC': {'population': 5218040, 'threeLargestCities': {'Columbia': 129272, 'Charleston': 120083, 'North Charleston': 97471}, 'nameofState': 'South Carolina', 'capital': 'Columbia'}, 'SD': {'population': 892717, 'threeLargestCities': {'Sioux Falls': 153888, 'Rapid City': 67956, 'Aberdeen': 26091}, 'nameofState': 'South Dakota', 'capital': 'Pierre'}, 'TN': {'population': 6886834, 'threeLargestCities': {'Memphis': 646889, 'Nashville': 626681, 'Knoxville': 178874}, 'nameofState': 'Tennessee', 'capital': 'Nashville'}, 'TX': {'population': 29360759, 'threeLargestCities': {'Houston': 2099451, 'San Antonio': 1327407, 'Dallas': 1197816}, 'nameofState': 'Texas', 'capital': 'Austin'}, 'UT': {'population': 3249879, 'threeLargestCities': {'Salt Lake City': 186440, 'West Valley City': 129480, 'Provo': 112488}, 'nameofState': 'Utah', 'capital': 'Salt Lake City'}, 'VT': {'population': 623347, 'threeLargestCities': {'Burlington': 42417, 'Essex': 19587, 'South Burlington': 17993}, 'nameofState': 'Vermont', 'capital': 'Montpelier'}, 'VA': {'population': 8590563, 'threeLargestCities': {'Virginia Beach': 437994, 'Norfolk': 242803, 'Chesapeake': 222209}, 'nameofState': 'Virginia', 'capital': 'Richmond'}, 'WA': {'population': 7693612, 'threeLargestCities': {'Seattle': 608660, 'Spokane': 208916, 'Tacoma': 198397}, 'nameofState': 'Washington', 'capital': 'Olympia'}, 'WV': {'population': 1784787, 'threeLargestCities': {'Charleston': 51400, 'Huntington': 49138, 'Parkersburg': 31492}, 'nameofState': 'West Virginia', 'capital': 'Charleston'}, 'WI': {'population': 5832655, 'threeLargestCities': {'Milwaukee': 594833, 'Madison': 233209, 'Green Bay': 104057}, 'nameofState': 'Wisconsin', 'capital': 'Madison'}, 'WY': {'population': 582328, 'threeLargestCities': {'Cheyenne': 59011, 'Casper': 55316, 'Laramie': 30816}, 'nameofState': 'Wyoming', 'capital': 'Cheyenne'}}

**Part 3** (4 points) given the information in the `states_info` dictionary, output the name of the state and its capital for those states whose capitals are among the three largest cities in the state. 
  * Use nested `for` loops: 
    * Go over the states;
    * For each state, go over the keys of the three largest cities dictionary value.

In [ ]:
# create a for loop to go over the state info dictionary to output name of the state and its capitals which are the three largest cities in the state.
for abbre in states_info:
    capital = states_info[abbre]["capital"] 
    threeLargestCities = states_info[abbre]["threeLargestCities"] 
    if capital in threeLargestCities:
        print(states_info[abbre]["nameofState"] + " -> " + states_info[abbre]["capital"])

Alabama -> Montgomery
Alaska -> Juneau
Arizona -> Phoenix
Arkansas -> Little Rock
Colorado -> Denver
Georgia -> Atlanta
Hawaii -> Honolulu
Idaho -> Boise
Indiana -> Indianapolis
Iowa -> Des Moines
Louisiana -> Baton Rouge
Massachusetts -> Boston
Minnesota -> St. Paul
Mississippi -> Jackson
Nebraska -> Lincoln
New Hampshire -> Concord
North Carolina -> Raleigh
North Dakota -> Bismarck
Ohio -> Columbus
Oklahoma -> Oklahoma City
Oregon -> Salem
Rhode Island -> Providence
South Carolina -> Columbia
Tennessee -> Nashville
Utah -> Salt Lake City
West Virginia -> Charleston
Wisconsin -> Madison
Wyoming -> Cheyenne


**Part 4** (4 points) given the information in the `states_info` dictionary, output the name of the states where the combined population of the three largest state cities is greater than 40% (or 0.4) of the overall state population. 
  * Use nested `for` loops: 
    * Go over the states;
    * For each state, go over the values of the three largest cities dictionary value.

In [ ]:
# create a for loop to output the name of the states where the combined population of the three largest state cities is greater than 40% (or 0.4) of the overall state population.
for abbre in states_info:
    population = states_info[abbre]["population"] 
    threeLargestCities = states_info[abbre]["threeLargestCities"] 
# initilize threecombined population to zero
    threePopulation = 0
    for x in threeLargestCities:
        threePopulation = threePopulation + threeLargestCities[x]

# check if combined population of the three largest state cities is greater than 40% (or 0.4)
    if threePopulation >= .4 * population:
        print(states_info[abbre]["nameofState"])

Alaska
Hawaii
New York
Ohio